### PR TITLE
Allow: providing translations for non-browser environment

### PR DESCRIPTION
**Pull request by danielbeardsley**
To support next.js, provide a setTranslations() export. Also, only complain on first use if translations aren't available.

### CODE REVIEW

**Comment by rjmccluskey** [comment]
CR 🍻

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Comment by danielbeardsley** [comment]
QA :+1: 

image

**Comment by rjmccluskey** [comment]
CR 🍻

**Comment by danielbeardsley** [comment]
I don't want to wait. I'll CR this tiny update myself.

CR :+1:

**Pull request merged**
